#!/bin/bash
cat $1 \
| sed 's/[[:space:]]*$//' \
| sed 's/\s*/ /' \
| sed 's/\*return/*Return/' \
| sed 's/^\*.*return/*Return/' \
| sed 's/^\*Main/*main/' \
| sed 's/^\*Main/*main/'\
| sed 's/^\*.*Main/*main/' \
| sed 's/^\s\t/\t/' \
| sed 's/\t\s/\t/' \
| sed 's/\n\n/\n/' \
| sed 's/\t\n\t\n/\n/' \
| sed 's/^\s//' \
| sed 's/{$/\n{\n/' \
| sed 's/}$/\n}/' \
| sed 's/[[:space:]]*$//' \
| sed 's/\s;$/;/' \
| sed 's/return(/return (/'\
| sed 's/\n\n/\n/' \
| sed 's/^\*Main/*main/' \
| sed 's/return.*:/Return:/' \
| sed 's/eturn\s:/eturn:/' \
| sed 's/\s*;/;/' \
| sed 's/;\s*/;/'\
| sed 's/return\s*(/return (/' \
| sed 's/(\s*/(/' \
| sed 's/\s*)/)/' \
| sed  's/\/\/\(.*\)/\/\*\1\*\//' > $1.lnt
echo "done, lintered file is $1.lnt"
